spring:
  datasource:
    url: jdbc:mysql://192.168.2.8:3306/vue_backend
    username: root
    password: 123456
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8181